### ISSUE TITLE
Getting AccessDenied for redirect domain

### ISSUE THREAD

**Issue by mxro** [cloudmaniac/terraform-aws-static-website#1]
Thanks for this! It creates all the resources without problem, including setup of certificates and CF distributions.

I found that after deploying some files to the root domain, resources from that domain are served without issue (in my case [javadelight.org](https://javadelight.org/)). However, when accessing the alternate domain name (in my case [www.javadelight.org](https://www.javadelight.org/)) I get an access denied error.

Tried a few things:

- Added a bucket policy to www.javadelight.org-redirect
- Added an index.html tp www.javadelight.org-redirect
- Double checked the -redirect bucket is set up for website redirection

This lead to the index.html being available - but all requests to not existing pages didn't go to the configured 404 page.

Would you have any pointers here? Have I missed something with the setup? Thank you!

**Comment by cloudmaniac** [comment]
Sorry for the delay. I never had such issue, did you figure what is the problem yet?

**Comment by mxro** [comment]
Thank you for getting back to me. Nope, didn't figure out the problem. It may have something to do with the policy for accessing S3 from CloudFront?

In my case, it wasn't so important to keep the content on S3 only accessible through CloudFront, so I configured S3 bucket as a CustomOrigin which supplied all the correct redirect headers etc. (but for this the S3 bucket needs to be public).

**Comment by cloudmaniac** [comment]
Weird...have you used the Terraform configuration as it's provided in my module? I explain more in details on the OAI / Origin configuration [here](https://cloudmaniac.net/wordpress-to-hugo-migration-2-hosting/) in the **_Hosting - Version 2_** section.

**Comment by mxro** [comment]
Thanks for the link to the article. I read it.

Yeah, I just used the module as-is. Just dropped in my domain name. As said in my original submission, everything got setup without any issues/errors by Terraform. Content on main website worked without any issues, just accessing the redirect domain resulted in the reported error.

I think it may have something to do with the same distinction between using the S3 website endpoint versus the S3 REST endpoint. As far as I could see from my tests, it appeared that the configured redirect domain in the redirect bucket only works when using the website endpoint. Thus as said, I switched to using that.

Really interesting if the module still works as is for your deployment (or interesting it didn't work in my case since it's all the same code!)! Really took me way longer to get this working (e.g. hosting a static website) than I anticipated, mostly thanks to the S3 REST vs S3 website endpoints ...!

**Comment by cloudmaniac** [comment]
I think I start to understand.

Was your issue happening when you try to access directly a specific page from the redirect domain? I just checked, and indeed it's not working. It's only working for the homepage.

E.g. (www.domain.com is the redirected domain, domain.com is the main one:
- www.domain.com redirects to domain.com
- www.domain.com/somepage/ has an AccessDenied error message

<img width="1098" alt="Screenshot 2020-06-15 at 11 24 43" src="https://user-images.githubusercontent.com/10382023/84641069-d6619d80-aefa-11ea-9c48-016791c3d11a.png">

**Comment by mxro** [comment]
Sorry for my late reply! Hmm, no I got the error even on the root page. Is it working for you with `www.domain.com/` with an added `/`?

**Comment by cloudmaniac** [comment]
Nope, not working with the added `/`

**Comment by marcusbelcher** [comment]
Firstly great work on the Terraform plugin. It has saved me a good amount of time, and nearly perfect! Nevertheless, I had the same experience as @mxro.  Content on the main root website worked without any issues (e.g. https://example.com), just accessing the redirect domain (e.g. https://www.example.com) resulted in the reported error. The CloudFront URL for the root bucket worked. The Cloudfront URL for the redirect bucket gave a permissions error. 

```
<Error>
   <Code>AccessDenied</Code>
   <Message>Access Denied</Message>
   <RequestId>4B45140D2193B557</RequestId>
   <HostId>zFZuZdPPqMtbsWzG563fbM68Wke38LB0O2UxumQxcxHvi9bnMqSu467iYJ7hNiJ+DYX+M61KqKE=</HostId>
</Error>
```

Using the latest AWS CLI, Terraform install. Below is my setup.tf file:

```
provider "aws" {
  version                 = "~> 2.0"
  region                  = "eu-west-1"
  shared_credentials_file = "~/.aws/credentials"
}

module "aws_static_website" {
  source = "cloudmaniac/static-website/aws"

  website-domain-main     = "example.com"
  website-domain-redirect = "example.com"
}
```

and my aws.credentials have:
- AWSLambdaFullAccess
- IAMFullAccess
- AmazonS3FullAccess
- CloudFrontFullAccess
- AmazonRoute53FullAccess
- AWSCertificateManagerFullAccess

and reported no errors in setting up. I did the follow commands in order:

- terraform init
- terraform apply


and then I uploaded an index.html and a 404.html to the root bucket manually. I then invalidated both the CloudFront distributions. 

I am going to reread this thread and tinker around with the S3 URLs :)

**Comment by marcusbelcher** [comment]
Within CloudFront for each distribution swapping the URL from:

- ${bucket_name}.s3.${region}.amazonaws.com
- http://example.com-root.s3.eu-west-1.amazonaws.com
- http://example.com-redirect.s3.eu-west-1.amazonaws.com

to 

- ${bucket_name}.s3-website.${region}.amazonaws.com
- http://example.com-root.s3-website.eu-west-1.amazonaws.com
- http://example.com-redirect.s3-website.eu-west-1.amazonaws.com

Appears to work, like the user above suggests. The only difference is I did not change bucket policies, or anything else. Now when a user goes to https://www.example.com they get redirected to https://example.com/index.html. I presume this was the expected behavior and is good for my needs. 

https://stackoverflow.com/questions/22740084/amazon-s3-redirect-and-cloudfront

**Comment by Dan-Tinsman** [comment]
I am also experiencing the issues mentioned above. I can reach my website via the following:

- example.com
- http://www.example.com
- https://example.com

but cannot reach it (403 - Forbidden) from:

- https://www.example.com
