### ISSUE TITLE
Error: no matching Route53Zone found

### ISSUE THREAD

**Issue by tim-hub** [cloudmaniac/terraform-aws-static-website#6]
Error: no matching Route53Zone found

  on .terraform/modules/aws_static_website/main.tf line 13, in data "aws_route53_zone" "main":
  13: data "aws_route53_zone" "main" {

- terraform 2.70.0 do nothing, follow the example usage, get this error

**Comment by cloudmaniac** [comment]
Could you provide some additional information? E.g.:

- what did you provided for the `website-domain-main` variable?
- is the domain already configured as a hosted zone on Route53?
- can you do a `terraform version` in the relevant directory and let me know the output?

Thx!

**Comment by tim-hub** [comment]
> Could you provide some additional information? E.g.:
> 
>     * what did you provided for the `website-domain-main` variable?
> 
>     * is the domain already configured as a hosted zone on Route53?
> 
>     * can you do a `terraform version` in the relevant directory and let me know the output?
> 
> 
> Thx!

no I did not do that

**Comment by tim-hub** [comment]
I do not even I need that

**Comment by tim-hub** [comment]
version is 2.70

**Comment by tim-hub** [comment]
do I have to do `is the domain already configured as a hosted zone on Route53?` manually?

**Comment by cloudmaniac** [comment]
Yes, you need an already configured domain in Route53, and you submit the domain name as an input variable to the module. This is mentioned and described in the README / documentation.
