### ISSUE TITLE
Sub domain + Sub sub domain pairs

### ISSUE THREAD

**Issue by TheNotary** [cloudmaniac/terraform-aws-static-website#8]
This is so great, but for testing, I attempted to use `example.mydomain.com` and `www.example.mydomain.com` but it isn't able to look up the route 53 zone.  Here's the line where it looks up the domain, and in my above case, I assume it tries to find a Route 53 zone of `example.mydomain.com` but one does not exist.  It would only find it if it looked for `mydomain.com` https://github.com/cloudmaniac/terraform-aws-static-website/blob/master/main.tf#L14 When I hard code the value, it seems to fix the issue.  Not sure how much coding is possible in terraform.

**Comment by cloudmaniac** [comment]
I see, I haven't thought about this use case. I'll see how to "extract" the root domain from the var.

**Comment by cloudmaniac** [comment]
This has been fixed in the new module version (based on the #10 merge request)
